// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANdWtEQ9Q4UW_l60LWZGWSMDYoUGm_Z0U',
    appId: '1:303648474574:android:2a4886e15520665329579f',
    messagingSenderId: '303648474574',
    projectId: 'smart-health-product-sca-a1389',
    storageBucket: 'smart-health-product-sca-a1389.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO9QTWuElcIsS81ph1wsfa45X6353mjTg',
    appId: '1:303648474574:ios:2069ae3462decfaa29579f',
    messagingSenderId: '303648474574',
    projectId: 'smart-health-product-sca-a1389',
    storageBucket: 'smart-health-product-sca-a1389.firebasestorage.app',
    iosClientId: '303648474574-dl2ejgtqmb1q9sm8attd5cr1qni7pifo.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartHealthProductScanner',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo5iSajDo3MPmz5xlbkCqxD0G9aEEgWJs',
    appId: '1:303648474574:web:ec6f51696ec654ab29579f',
    messagingSenderId: '303648474574',
    projectId: 'smart-health-product-sca-a1389',
    authDomain: 'smart-health-product-sca-a1389.firebaseapp.com',
    storageBucket: 'smart-health-product-sca-a1389.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo5iSajDo3MPmz5xlbkCqxD0G9aEEgWJs',
    appId: '1:303648474574:web:14ce85f6efb5b44b29579f',
    messagingSenderId: '303648474574',
    projectId: 'smart-health-product-sca-a1389',
    authDomain: 'smart-health-product-sca-a1389.firebaseapp.com',
    storageBucket: 'smart-health-product-sca-a1389.firebasestorage.app',
  );

}